repos:
  # --- General code hygiene ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict

  # --- Python linting & formatting (backend) ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        name: "Ruff Lint & Format"
        args: [--fix]
        files: \.py$

  # --- Frontend formatting (Prettier) ---
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: "Prettier Format Auto-Fix"
        args: [--write]
        files: 'frontend/.*\.(js|jsx|ts|tsx|json|css|md)$'
        exclude: 'node_modules/|build/|dist/|\.next/'

  # --- Secret scanning ---
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
        exclude: >
          (?x)(
            \.env\.test|
            \.env\.example|
            \.secrets\.baseline|
            node_modules|
            dist|
            build|
            backend/tests/
          )

  # --- Frontend linting (custom) ---
  - repo: local
    hooks:
      - id: frontend-lint
        name: "Frontend Lint"
        entry: bash -c "cd frontend && npm run lint"
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
