"""Add Alert table

Revision ID: 2f4fc3d2e31b
Revises: 09b2f0d7d240
Create Date: 2025-11-12 13:11:41.712539

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f4fc3d2e31b" # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "09b2f0d7d240"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assigned_to_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "severity", sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", name="alertseverity"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INVESTIGATING", "RESOLVED", "ACKNOWLEDGED", name="alertstatus"),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("src_ip", sa.String(length=50), nullable=True),
        sa.Column("dst_ip", sa.String(length=50), nullable=True),
        sa.Column("dst_port", sa.Integer(), nullable=True),
        sa.Column("model_output", sa.JSON(), nullable=True),
        sa.Column(
            "flow_timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_to_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_dst_port"), "alerts", ["dst_port"], unique=False)
    op.create_index(op.f("ix_alerts_id"), "alerts", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alerts_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_dst_port"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
