"""Add flow_data column to alerts table

Revision ID: 8891f2a504bb
Revises: 2f4fc3d2e31b
Create Date: 2025-11-15 16:47:47.288829

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8891f2a504bb' # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = '2f4fc3d2e31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('flow_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'flow_data')
    # ### end Alembic commands ###
