"""Add mfa recovery fields to user model

Revision ID: a50258190476
Revises: 761fb78e480a
Create Date: 2025-10-12 00:34:24.027999

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a50258190476"
down_revision: Union[str, Sequence[str], None] = "761fb78e480a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("mfa_recovery_token", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("mfa_recovery_token_expires", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "mfa_recovery_token_expires")
    op.drop_column("users", "mfa_recovery_token")
    # ### end Alembic commands ###
