name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ----------------------
  # Backend (FastAPI) checks
  # ----------------------
  backend-lint:
    name: Backend Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv & Ruff
        run: |
          pipx install uv

      - name: Set up virtual environment
        run: |
          uv venv
          source .venv/bin/activate

      - name: Install Ruff
        run: |
          uv pip install ruff

      - name: Run Ruff lint & format checks
        run: |
          # Lint and fail on errors
          ruff check backend

  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Install dependencies (uv)
        run: |
          cd backend
          uv sync --extra dev --extra test

      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}/backend/
        run: uv pip install pytest pytest-cov httpx && pytest -v --cov-report=xml backend/tests/

      - name: Display coverage in GitHub summary
        if: success()
        run: |
          coverage report -m >> $GITHUB_STEP_SUMMARY

  # ----------------------
  # Frontend (Next.js) checks
  # ----------------------
  frontend:
    name: Frontend Lint & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run ESLint
        working-directory: frontend
        run: npm run lint

      - name: Build Next.js app
        working-directory: frontend
        run: npm run build
